services:
  backend-js:
    build: .
    container_name: backend-js
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - mariadb

  mariadb:
    image: linuxserver/mariadb:10.6.18
    container_name: backend-mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mariadb_data:/config
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Jakarta

volumes:
  mariadb_data:
