version: "3.8"

services:
  backend-js:
    build: .
    container_name: backend-js
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    container_name: backend-mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW

volumes:
  mariadb_data:
