services:
  backend-js:
    build: .
    container_name: backend-js
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    depends_on:
      - mariadb

  mariadb:
    image: yobasystems/alpine-mariadb:10.5
    container_name: backend-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: backend_db
      MYSQL_USER: backend
      MYSQL_PASSWORD: backendpass
      TZ: Asia/Jakarta
    ports:
      - "3307:3306" # ⬅️ INI KUNCINYA
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
