name: Deploy backend-js (Orange Pi)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy with docker-compose
        run: |
          cd /home/mufkimustache/projects/backend-js

          echo "ğŸ”„ Pull latest code"
          git pull origin master

          echo "ğŸ³ Docker compose deploy"
          docker compose down
          docker compose build
          docker compose up -d

          echo "âœ… Deploy finished"
