name: Deploy backend-js (Orange Pi)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Deploy with docker-compose
        run: |
          cd /home/mufkimustache/projects/backend-js

          echo "ğŸ”„ Pull latest code"
          git pull origin master

          echo "ğŸ³ Build image"
          docker compose build

          echo "ğŸ“¦ Run migrations"
          docker compose run --rm backend-js npx sequelize-cli db:migrate

          echo "ğŸš€ Restart services"
          docker compose down
          docker compose up -d

          echo "âœ… Deploy finished"
