name: Deploy backend-js (Orange Pi)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build & Deploy Docker
        run: |
          echo "ğŸ“¦ Pull latest code"
          git pull origin master

          echo "ğŸ›‘ Stop old container"
          docker stop backend-js || true
          docker rm backend-js || true

          echo "ğŸ³ Build new image"
          docker build -t backend-js .

          echo "ğŸš€ Run new container"
          docker run -d \
            --name backend-js \
            -p 3001:3001 \
            --restart unless-stopped \
            backend-js

          echo "âœ… Deploy finished"
